#!/usr/bin/env python3
# gen_phrasebank.py — (re)generate src/phrasebank.h for the on-device voice
# engine. Reads the phrasebank straight out of src/main.cpp and precomputes each
# line's clip filename so the device plays the right data/audio/*.mp3.
#
#   OWNER="Tasfia" python3 tools/gen_phrasebank.py   # must match gen_voice.py's OWNER
#
# Warns about any missing clips (run gen_voice.py first).
import os, sys, re
sys.path.insert(0, os.path.dirname(__file__))
import voicelib as V

PROJ  = V.project_root()
SRC   = os.path.join(PROJ, "src", "main.cpp")
AUD   = os.path.join(PROJ, "data", "audio")
OUT   = os.path.join(PROJ, "src", "phrasebank.h")
OWNER = os.environ.get("OWNER", V.OWNER_DEFAULT)

src = open(SRC, encoding="utf-8").read()
i = src.find("const B=["); j = src.find("];", i)
Bblock = src[i:j]

buckets = []
for m in re.finditer(r"\{id:'([^']+)',prio:(\d+),mood:'([^']+)'.*?lines:\[(.*?)\]\}", Bblock, re.S):
    bid, prio, mood, blob = m.groups()
    if bid == "milestone":                     # dynamic {{ms}} — no fixed clip
        continue
    lines = re.findall(r'"([^"]*)"', blob)
    buckets.append((bid, int(prio), mood, lines))

def cstr(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

out = [f"// AUTO-GENERATED by tools/gen_phrasebank.py (OWNER={OWNER!r}) — do not edit by hand.",
       "#pragma once",
       "struct PBLine { const char* clip; const char* text; };",
       "struct PBBucket { const char* id; uint8_t prio; const char* mood; const PBLine* lines; uint8_t n; };",
       ""]
decls = []; missing = 0
for bid, prio, mood, lines in buckets:
    arr = []
    for raw in lines:
        cid = V.clip_id(raw, OWNER)
        if not os.path.exists(os.path.join(AUD, cid + ".mp3")):
            print(f"  !! MISSING clip {cid}.mp3  [{bid}] {raw[:36]}"); missing += 1; continue
        arr.append((cid, V.apply_owner(raw, OWNER)))
    if not arr:
        continue
    out.append(f"static const PBLine PB_{bid}[] = {{")
    for cid, disp in arr:
        out.append(f'  {{ "/audio/{cid}.mp3", {cstr(disp)} }},')
    out.append("};")
    decls.append((bid, prio, mood, len(arr)))

out.append("\nstatic const PBBucket PHRASEBANK[] = {")
for bid, prio, mood, n in decls:
    out.append(f'  {{ "{bid}", {prio}, "{mood}", PB_{bid}, {n} }},')
out.append("};")
out.append(f"static const int PHRASEBANK_N = {len(decls)};")

open(OUT, "w").write("\n".join(out) + "\n")
print(f"wrote {OUT}: {len(decls)} buckets, {missing} missing clips")
if missing:
    print("  -> run tools/gen_voice.py (same OWNER) first to make the missing clips.")
