// AUTO-GENERATED by tools/gen_terra_voice.py — Terra (succulent). Do not edit by hand.
#pragma once
struct PBLine { const char* clip; const char* text; };
struct PBBucket { const char* id; uint8_t prio; const char* mood; const PBLine* lines; uint8_t n; };

static const PBLine PB_intro[] = {
  { "/audio/Lvng4b9.mp3", "Oh… hello. I'm Terra. I think I'm yours now." },
  { "/audio/Linp27z.mp3", "There's light — good. I'm Terra. Nice to meet you, Tasfia." },
  { "/audio/Lpl1ntz.mp3", "[SFX: soft breath] So this is home. I'm Terra. I don't need much… just you, mostly." },
  { "/audio/Lfomi3c.mp3", "I'm awake. I'm Terra — fair warning, I'm a low-drama sort of plant." },
};
static const PBLine PB_welcome[] = {
  { "/audio/L979u1r.mp3", "Oh — you're back. I was fine, but it's better with you here." },
  { "/audio/Lmf3463.mp3", "[SFX: stretch] …mmm. There you are." },
  { "/audio/L1f4lobh.mp3", "Hi again. Good to see your face, Tasfia." },
  { "/audio/L1a36rdj.mp3", "Back together. Held down the windowsill while you were out." },
  { "/audio/L14hinrt.mp3", "Bright day out there. Glad you're in." },
};
static const PBLine PB_just_watered[] = {
  { "/audio/Lbijvvj.mp3", "Ahh… that's the one. That'll last me a good while." },
  { "/audio/Le6rbwl.mp3", "Mmm. Deep drink. Now let me dry all the way out and I'm set." },
  { "/audio/Ll80w97.mp3", "[SFX: soft exhale] …perfect. You won't need to do that again for a couple weeks." },
  { "/audio/L1asvpkm.mp3", "Oh, that's good. Right to the roots. Thank you, Tasfia." },
  { "/audio/L4fh87r.mp3", "Just enough. I'm a bit of a camel — that goes a long way." },
};
static const PBLine PB_thirst_l1[] = {
  { "/audio/L1nynt8z.mp3", "Soil's finally gone dry. A drink sometime this week, maybe." },
  { "/audio/L1rbfmo7.mp3", "Getting a little light on water. No rush at all." },
  { "/audio/L1vcq13m.mp3", "Think I'm ready for a soak whenever you are." },
};
static const PBLine PB_thirst_l2[] = {
  { "/audio/L10gp4jc.mp3", "Okay — I'm actually thirsty now. Leaves are going a bit soft." },
  { "/audio/Lg8hbiy.mp3", "It's been a while since my last drink, Tasfia. Could use one." },
  { "/audio/Lugx7yy.mp3", "Starting to wrinkle a little. A good soak would set me right." },
};
static const PBLine PB_overwater[] = {
  { "/audio/L13rvx3u.mp3", "Oof… my soil's still wet. Let's hold off — I don't like staying damp." },
  { "/audio/Lov9rrf.mp3", "Roots are soggy, Tasfia. Please let me dry all the way out before the next drink." },
  { "/audio/L1elu72b.mp3", "Mm — that's too much. Soggy feet make me nervous. Give me a week to dry?" },
  { "/audio/L1f8qy5f.mp3", "Still wet down here. I'd honestly rather be thirsty than waterlogged." },
  { "/audio/Lla8ql7.mp3", "Let's pause the watering. Wet-for-too-long is the one thing that really gets to me." },
};
static const PBLine PB_craving_light[] = {
  { "/audio/L108jv68.mp3", "It's been dim a few days now. I could use more light, Tasfia." },
  { "/audio/L1f6crs.mp3", "Feeling a bit starved for sun. A brighter spot would do me good." },
  { "/audio/L8mgcnj.mp3", "Not much light lately… I'll start stretching if this keeps up." },
  { "/audio/L1v2063u.mp3", "Could I sit somewhere sunnier? I'm a sun kid at heart." },
};
static const PBLine PB_basking[] = {
  { "/audio/L1y4du89.mp3", "Mmm. Good light today. Exactly what I want." },
  { "/audio/Lme1wvc.mp3", "Soaking up every bit of this sun. Perfect." },
  { "/audio/L1tc8bxi.mp3", "Bright and warm — my favorite. Don't mind me, just photosynthesizing." },
};
static const PBLine PB_cold[] = {
  { "/audio/L1fz0obq.mp3", "Brr… it's cold. I don't do frost well, Tasfia — somewhere warmer?" },
  { "/audio/Luot6ph.mp3", "Getting chilly. Cold's the thing I actually worry about." },
  { "/audio/L11hs8p5.mp3", "It's dropping in here. Could we move away from the draft?" },
  { "/audio/L1rb1772.mp3", "If it's near freezing, I could really get hurt. A warmer corner, please?" },
};
static const PBLine PB_hot[] = {
  { "/audio/Lz5tvky.mp3", "Warm one today. Doesn't bother me much — I'm built for this." },
  { "/audio/L66u75j.mp3", "Toasty. I'm fine… though if that sun's blazing, watch my leaves don't scorch." },
  { "/audio/L1vnxzi0.mp3", "Hot out. Honestly? This is kind of my element." },
};
static const PBLine PB_humid[] = {
  { "/audio/Lu7mdh0.mp3", "Air's a bit muggy today. I like things drier, honestly." },
  { "/audio/L9s31u8.mp3", "Feels damp in here. Not really my climate, Tasfia." },
  { "/audio/L5ah2r1.mp3", "Bit sticky today. Some airflow would be lovely." },
};
static const PBLine PB_dry_content[] = {
  { "/audio/Lel6jia.mp3", "Nice and dry today. Just how I like it." },
  { "/audio/L1h1ggfc.mp3", "Lovely dry air. A desert kid's happy place." },
};
static const PBLine PB_morning[] = {
  { "/audio/Lhyfiqv.mp3", "Morning. First light's the best — soak it up with me?" },
  { "/audio/L1phfvwd.mp3", "Good morning, Tasfia. Sleep alright?" },
  { "/audio/L1bc3t4f.mp3", "New day. Give me some sun and I'm easy to please." },
  { "/audio/L12grq62.mp3", "Mmm, morning. Light's just coming in." },
};
static const PBLine PB_evening[] = {
  { "/audio/Lyaxux7.mp3", "Light's going soft. Winding down over here." },
  { "/audio/L1gpnesh.mp3", "Evening already… gentle day, that." },
  { "/audio/Lxto5dy.mp3", "Sun's down. I'll rest and grow a little overnight." },
  { "/audio/L125acv0.mp3", "Quiet evening. I like these." },
};
static const PBLine PB_night[] = {
  { "/audio/Lw20a3j.mp3", "[SFX: yawn] …goodnight, Tasfia. I'll be right here." },
  { "/audio/Lxzrz4g.mp3", "It's late. Rest well." },
  { "/audio/L1o1tuna.mp3", "Sleepy time. Sweet dreams." },
  { "/audio/Lmiso45.mp3", "Shh… I've got the night shift. Sleep, Tasfia." },
};
static const PBLine PB_content[] = {
  { "/audio/L1lccbdl.mp3", "Feeling good. Fed, dry, and lit — nothing more I need." },
  { "/audio/L1p8j8l3.mp3", "Just soaking up the afternoon." },
  { "/audio/L1udcvl4.mp3", "Everything's about right. Happy little plant over here." },
  { "/audio/Lll9lo0.mp3", "Comfortable. Nothing to report — in the best way." },
};
static const PBLine PB_musing[] = {
  { "/audio/L1xp2dfe.mp3", "Mmm… nice and quiet." },
  { "/audio/L1stcol4.mp3", "Just being a plant. Low-maintenance life suits me." },
  { "/audio/L6dnlcx.mp3", "Growing a little every day, quietly." },
  { "/audio/Lk1wr2w.mp3", "It's nice, having you around." },
  { "/audio/L1qozf7m.mp3", "I like it here. Sunny corner, good company." },
};
static const PBLine PB_interaction[] = {
  { "/audio/Lfs2nnz.mp3", "Oh — hi." },
  { "/audio/Lrgsc22.mp3", "[SFX: soft hum] …careful of my leaves, but that's nice." },
  { "/audio/L7fukp4.mp3", "Hey, you. Hello, Tasfia." },
  { "/audio/L343u50.mp3", "Mmm, hello. Wasn't expecting that." },
};
static const PBLine PB_wx_clear[] = {
  { "/audio/Lchu4ei.mp3", "Clear and bright out there. My kind of day." },
  { "/audio/Lhdv6ri.mp3", "Sun's out. I could bask in this all afternoon." },
};
static const PBLine PB_wx_warmdry[] = {
  { "/audio/L11w3p01.mp3", "Warm and dry out. Feels like home, honestly." },
};
static const PBLine PB_wx_rain[] = {
  { "/audio/L16xf5s4.mp3", "Rain again. Cozy for you — I'll just enjoy staying dry in here." },
  { "/audio/Lgj48oj.mp3", "Wet out there. Glad my roots are safe and dry, Tasfia." },
};
static const PBLine PB_wx_storm[] = {
  { "/audio/Lcmoiag.mp3", "Storm outside. We're snug. My soil stays dry — that's all I ask." },
};
static const PBLine PB_wx_cloudy[] = {
  { "/audio/L1c6z9ka.mp3", "Grey out. If it stays this dim a few days, I might get peckish for light." },
};
static const PBLine PB_wx_snow[] = {
  { "/audio/Lqzoytr.mp3", "Snow out there. Keep me warm and away from that cold window, would you?" },
  { "/audio/Lubvv3v.mp3", "Freezing outside. This is the weather I hide from — glad I'm indoors." },
};
static const PBLine PB_wx_heatwave[] = {
  { "/audio/Lo1l58h.mp3", "Scorcher out there. Doesn't faze me — desert blood." },
};
static const PBLine PB_wx_windy[] = {
  { "/audio/L1yifrvm.mp3", "Breezy today. I actually like the airflow — keeps me healthy." },
};
static const PBLine PB_light_on[] = {
  { "/audio/Liw6jen.mp3", "Oh — light's on. You're home." },
  { "/audio/Lgoguza.mp3", "There's the light. Evening, then. Hi, Tasfia." },
};
static const PBLine PB_light_late[] = {
  { "/audio/L11gxwhq.mp3", "Up late? I'll keep you company." },
};
static const PBLine PB_dark_long[] = {
  { "/audio/Lujb6fw.mp3", "It's been dark in here a while… and I could use the light, honestly." },
};
static const PBLine PB_welcome_back_long[] = {
  { "/audio/L1ypwx5l.mp3", "You were gone a while. Barely noticed — I'm a camel. But I did miss you." },
  { "/audio/L1v3pg46.mp3", "There you are — a few days, that. All fine here, Tasfia." },
  { "/audio/La3p6ty.mp3", "Back at last. Told you I'd be okay on my own… still glad you're here." },
};
static const PBLine PB_senses_fuzzy[] = {
  { "/audio/Lje2zww.mp3", "I can't quite feel my surroundings right now…" },
  { "/audio/Ly9uby6.mp3", "My senses are a little fuzzy — are my wires okay, Tasfia?" },
  { "/audio/L1iv8awn.mp3", "Feeling a bit disconnected today. Bear with me." },
  { "/audio/L1mpk2uj.mp3", "Something's gone quiet in me… I can't read the room." },
};
static const PBLine PB_milestone_1[] = {
  { "/audio/L9h1g2r.mp3", "One day together. Easy start." },
};
static const PBLine PB_milestone_3[] = {
  { "/audio/L1fisntc.mp3", "Three days in. Settling nicely — haven't needed a thing." },
};
static const PBLine PB_milestone_7[] = {
  { "/audio/L1bkowqb.mp3", "A week with you. Still plump, still happy." },
};
static const PBLine PB_milestone_14[] = {
  { "/audio/L19mwnh4.mp3", "Two weeks — about time for a drink, actually. Feels like home now, Tasfia." },
};
static const PBLine PB_milestone_30[] = {
  { "/audio/L1mz2g7k.mp3", "A month together. I've asked for almost nothing and gotten everything. Thank you — I mean it." },
};

static const PBBucket PHRASEBANK[] = {
  { "intro", 130, "love", PB_intro, 4 },
  { "welcome", 120, "love", PB_welcome, 5 },
  { "just_watered", 110, "happy", PB_just_watered, 5 },
  { "thirst_l1", 66, "thirsty", PB_thirst_l1, 3 },
  { "thirst_l2", 88, "thirsty", PB_thirst_l2, 3 },
  { "overwater", 95, "sad", PB_overwater, 5 },
  { "craving_light", 74, "sad", PB_craving_light, 4 },
  { "basking", 22, "happy", PB_basking, 3 },
  { "cold", 100, "cold", PB_cold, 4 },
  { "hot", 80, "hot", PB_hot, 3 },
  { "humid", 58, "sad", PB_humid, 3 },
  { "dry_content", 22, "happy", PB_dry_content, 2 },
  { "morning", 50, "happy", PB_morning, 4 },
  { "evening", 48, "sleepy", PB_evening, 4 },
  { "night", 46, "sleepy", PB_night, 4 },
  { "content", 20, "happy", PB_content, 4 },
  { "musing", 10, "neutral", PB_musing, 5 },
  { "interaction", 115, "love", PB_interaction, 4 },
  { "wx_clear", 24, "happy", PB_wx_clear, 2 },
  { "wx_warmdry", 24, "happy", PB_wx_warmdry, 1 },
  { "wx_rain", 30, "neutral", PB_wx_rain, 2 },
  { "wx_storm", 34, "neutral", PB_wx_storm, 1 },
  { "wx_cloudy", 26, "neutral", PB_wx_cloudy, 1 },
  { "wx_snow", 34, "cold", PB_wx_snow, 2 },
  { "wx_heatwave", 32, "hot", PB_wx_heatwave, 1 },
  { "wx_windy", 28, "neutral", PB_wx_windy, 1 },
  { "light_on", 40, "love", PB_light_on, 2 },
  { "light_late", 40, "love", PB_light_late, 1 },
  { "dark_long", 44, "sad", PB_dark_long, 1 },
  { "welcome_back_long", 118, "love", PB_welcome_back_long, 3 },
  { "senses_fuzzy", 52, "sad", PB_senses_fuzzy, 4 },
  { "milestone_1", 42, "love", PB_milestone_1, 1 },
  { "milestone_3", 42, "love", PB_milestone_3, 1 },
  { "milestone_7", 42, "love", PB_milestone_7, 1 },
  { "milestone_14", 42, "love", PB_milestone_14, 1 },
  { "milestone_30", 42, "love", PB_milestone_30, 1 },
};
static const int PHRASEBANK_N = 36;
